# Generated by Django 4.2.4 on 2024-11-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('booked_on', models.DateTimeField()),
                ('category', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=100)),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_country', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('delivered_to', models.CharField(max_length=100)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_address', models.TextField()),
                ('sender_mobile', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_address', models.TextField()),
                ('receiver_mobile', models.CharField(max_length=20)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('content_of_shipment', models.TextField()),
            ],
        ),
    ]
